stages:
  - verify

formalcloud_terraform_gate:
  stage: verify
  image: python:3.11-slim
  before_script:
    - python -m pip install --upgrade pip
    - pip install formal-cloud
  script:
    - terraform show -json tfplan.binary > tfplan.json
    - |
      formal-cloud verify terraform \
        --policies policy/policies.yaml \
        --plan tfplan.json \
        --workspace "$CI_COMMIT_REF_NAME" \
        --out artifacts/terraform-certificate.json \
        --trace artifacts/terraform-trace.jsonl
    - |
      formal-cloud export junit \
        --certificate artifacts/terraform-certificate.json \
        --out artifacts/terraform.junit.xml
    - |
      formal-cloud export sarif \
        --certificate artifacts/terraform-certificate.json \
        --out artifacts/terraform.sarif.json
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - artifacts/
    reports:
      junit: artifacts/terraform.junit.xml
